# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 10:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['state', 'estimate']},
        ),
    ]
